image: archlinux
packages:
  - rustup
sources:
  - https://github.com/gsspdev/modsynth.git
tasks:
  - setup: |
      rustup toolchain install nightly stable
      cd gssp-rust-template/
      rustup run stable cargo fetch
  - stable: |
      rustup default stable
      cd gssp-rust-template/
      cargo build --verbose
      cargo test --verbose
  - nightly: |
      rustup default nightly
      cd gssp-rust-template\
      cargo build --verbose ||:
      cargo test --verbose ||:
  - docs: |
      cd gssp-rust-template/
      rustup run stable cargo doc --no-deps
      rustup run nightly cargo doc --no-deps ||:
