name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-stable

    steps:
    - uses: actions/checkout@v3
    - name: Alsa
      run: apt-get -y install alsa-tools
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
